In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
## Sentences
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
## Define the vocabulary size
voc_size = 10000

In [ ]:
## one_hot representation
one_hot_repr = [one_hot(words,voc_size) for words in sent]

In [ ]:
one_hot_repr

[[8065, 9215, 687, 1716],
 [8065, 9215, 687, 7254],
 [8065, 9318, 687, 9825],
 [3771, 959, 3170, 3313, 8683],
 [3771, 959, 3170, 3313, 2939],
 [4757, 8065, 9074, 687, 4013],
 [4450, 334, 8575, 3313]]

In [ ]:
## Word embedding representation

from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

In [ ]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8065 9215  687 1716]
 [   0    0    0    0 8065 9215  687 7254]
 [   0    0    0    0 8065 9318  687 9825]
 [   0    0    0 3771  959 3170 3313 8683]
 [   0    0    0 3771  959 3170 3313 2939]
 [   0    0    0 4757 8065 9074  687 4013]
 [   0    0    0    0 4450  334 8575 3313]]


In [ ]:
## feature representation
dim = 10
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length,trainable=True))
model.compile('adam','mse')

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step


array([[[-6.57856464e-03, -2.69352552e-02, -1.66289322e-02,
         -2.17239615e-02, -1.86955109e-02,  2.46664025e-02,
          3.90720628e-02, -2.89843567e-02,  4.58039977e-02,
          4.52348851e-02],
        [-6.57856464e-03, -2.69352552e-02, -1.66289322e-02,
         -2.17239615e-02, -1.86955109e-02,  2.46664025e-02,
          3.90720628e-02, -2.89843567e-02,  4.58039977e-02,
          4.52348851e-02],
        [-6.57856464e-03, -2.69352552e-02, -1.66289322e-02,
         -2.17239615e-02, -1.86955109e-02,  2.46664025e-02,
          3.90720628e-02, -2.89843567e-02,  4.58039977e-02,
          4.52348851e-02],
        [-6.57856464e-03, -2.69352552e-02, -1.66289322e-02,
         -2.17239615e-02, -1.86955109e-02,  2.46664025e-02,
          3.90720628e-02, -2.89843567e-02,  4.58039977e-02,
          4.52348851e-02],
        [-4.20826450e-02, -3.26868296e-02,  3.85363735e-02,
          8.80213827e-03, -1.65667385e-03,  5.17591834e-05,
          9.14568827e-03,  2.38878168e-02,  5.469869

In [ ]:
## feature representation
# Predict on a single sample, reshaping it to include a batch dimension
prediction = model.predict(np.expand_dims(embedded_docs[0], axis=0))
print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step
[[[-6.5785646e-03 -2.6935255e-02 -1.6628932e-02 -2.1723961e-02
   -1.8695511e-02  2.4666402e-02  3.9072063e-02 -2.8984357e-02
    4.5803998e-02  4.5234885e-02]
  [-6.5785646e-03 -2.6935255e-02 -1.6628932e-02 -2.1723961e-02
   -1.8695511e-02  2.4666402e-02  3.9072063e-02 -2.8984357e-02
    4.5803998e-02  4.5234885e-02]
  [-6.5785646e-03 -2.6935255e-02 -1.6628932e-02 -2.1723961e-02
   -1.8695511e-02  2.4666402e-02  3.9072063e-02 -2.8984357e-02
    4.5803998e-02  4.5234885e-02]
  [-6.5785646e-03 -2.6935255e-02 -1.6628932e-02 -2.1723961e-02
   -1.8695511e-02  2.4666402e-02  3.9072063e-02 -2.8984357e-02
    4.5803998e-02  4.5234885e-02]
  [-4.2082645e-02 -3.2686830e-02  3.8536374e-02  8.8021383e-03
   -1.6566738e-03  5.1759183e-05  9.1456883e-03  2.3887817e-02
    5.4698698e-03 -4.4907331e-03]
  [-4.5231819e-02  1.0228865e-03  8.6587779e-03 -2.0853806e-02
   -2.7454011e-03  2.2311322e-03 -1.9187165e-02  7.2205551e-03
    1.8325638e-02  4.9655166e-02]
  